name = "gitcord-forum"
main = "./build/index.js"
workers_dev = true
compatibility_date = "2025-05-05"

kv_namespaces = [{ binding = "DB", id = "293ac4c6310245ee8b87c7a070ae24b2" }]

[build]
command = "npm run build"

[observability.logs]
enabled = true

[placement]
mode = "smart"

[vars]
# Sensitive data should be stored in the worker itself as an encrypted value... in other terms: NOT IN THIS FILE!
# Method 1 is to use the `wrangler` command: `wrangler secret put <key>` where key is the environment variable name
# Method 2 is to put them in through the workers dashboard
#
# Sensitive environment variables:
# - GITHUB_WEBHOOK_SECRET - your secret for webhooks
# - DISCORD_WEBHOOK       - your discord webhook link (needs to be in a forum channel!)
# All sensitive variables get a default value of "" just so the worker doesn't crash

IGNORED_USERS = "" # Comma-separated list of usernames (e.g. "promise,renovate[bot]")
IGNORE_BOTS = "true" # Keeping this "true" will ignore bots
FALLBACK_URL = "https://github.com/biaw/gitcord-forum" # Fallback URL for when a user types the worker address
